# Usage:
#     run_puppet_agent.ps1 <puppet-svr-host-port>

param(
    [Parameter()]
    [ValidateNotNullOrEmpty()]
    [String]$puppetSvrHostPort
)

$usage = @"
Usage:
    run_puppet_agent.ps1 <puppet-svr-host-port>

Example:
    run_puppet_agent.ps1 34567
"@

# Check for required parameter
if (-not($puppetSvrHostPort)) {
    echo "ERROR: <puppet-svr-host-port> not provided on command line"
    echo $usage
    exit 1
}


# Clean any previous SSL certificates that were generated by the
# Puppet master
rm -r /ProgramData/PuppetLabs/puppet/etc/ssl

# Run the puppet agent
puppet agent -t --verbose --debug --masterport $puppetSvrHostPort
