services:
  puppet:
    image: puppet/puppetserver:${PUPPET_SERVER_TAG:-latest}
    # For version 8:
    # image:  ghcr.io/openvoxproject/openvoxserver:8
    # puppet/puppetservice now redirects via dockerhub deprecation to https://github.com/OpenVoxProject/container-openvoxserver
    platform: linux/amd64
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      # The mounted onto path '/conjur' is a proxy location that allows us to decide, at
      # runtime, between installing the packaged module or using the module source.
      - ../../.:/conjur
    environment:
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETDB_SERVER_URLS=https://puppet-db:8081
      - CA_ALLOW_SUBJECT_ALT_NAMES=true
      - DNS_ALT_NAMES=puppet,puppet-compiler
    depends_on:
      - puppet-db

  puppet-compiler:
    image: puppet/puppetserver:${PUPPET_SERVER_TAG:-latest}
    platform: linux/amd64
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      # The mounted onto path '/conjur' is a proxy location that allows us to decide, at
      # runtime, between installing the packaged module or using the module source.
      - ../../.:/conjur
    environment:
      - CA_ENABLED=false
      - CA_HOSTNAME=puppet
      - PUPPETSERVER_HOSTNAME=puppet-compiler
      - PUPPETDB_SERVER_URLS=https://puppet-db:8081
      - DNS_ALT_NAMES=puppet,puppet-compiler
    depends_on:
      - puppet
      - puppet-db

  puppet-db:
    image: puppet/puppetdb
    platform: linux/amd64
    environment:
      - CERTNAME=puppet-db
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETDB_POSTGRES_HOSTNAME=puppet-pg
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
      - PUPPETDB_POSTGRES_DATABASE=puppetdb-main
      - DNS_ALT_NAMES=puppet-db
    ports:
      - 8080
      - 8081
    depends_on:
      - puppet-pg

  puppet-pg:
    image: postgres:latest
    platform: linux/amd64
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb-main
    expose:
      - 5432

  puppetboard:
    image: puppet/puppetboard
    platform: linux/amd64
    ports:
      - 8081:8000

  puppetexplorer:
    image: puppet/puppetexplorer
    platform: linux/amd64
    ports:
      - 8080:80
    read_only: true

  conjur:
    image: cyberark/conjur
    platform: linux/amd64
    ports:
      - 80
    environment:
      CONJUR_ADMIN_PASSWORD: ADmin123!!!!
      DATABASE_URL: postgres://postgres:SuperSecretPg@conjur-db/postgres
      CONJUR_DATA_KEY: testing//testing//testing//testing//testing=
    #volumes:
    #  - .:/src:ro
    #working_dir: /src
    command: server
    depends_on:
      - conjur-db


  conjur-https:
    image: nginx:alpine
    platform: linux/amd64
    ports:
      - 8443
    volumes:
      - ./https_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./https_config/conjur.conf:/etc/nginx/sites-enabled/conjur.conf:ro
      - ./https_config/dhparams.pem:/etc/nginx/dhparams.pem:ro
      - ./https_config/conjur.crt:/cert/tls.crt:ro
      - ./https_config/conjur.key:/cert/tls.key:ro
      - ./https_config/ca.crt:/ca/tls.crt:ro
    depends_on:
      - conjur
    networks:
      default:
        aliases:
          - conjur.cyberark.com

  conjur-db:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_PASSWORD: SuperSecretPg
    ports:
      - 8432:5432
  cli:
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_APPLIANCE_URL: http://conjur
    image: cyberark/conjur-cli
    platform: linux/amd64
    entrypoint: sleep
    command: infinity
    volumes:
      - .:/src:ro
