services:
  puppet:
    image: ghcr.io/openvoxproject/openvoxserver:${PUPPET_SERVER_TAG}
    platform: linux/amd64
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      # The mounted onto path '/conjur' is a proxy location that allows us to decide, at
      # runtime, between installing the packaged module or using the module source.
      - ../../.:/conjur
    environment:
      - OPENVOXSERVER_HOSTNAME=puppet
      - CA_ALLOW_SUBJECT_ALT_NAMES=true
      - DNS_ALT_NAMES=puppet,puppet-compiler
      - HIERACONFIG=/etc/puppetlabs/code/hiera.yaml
    depends_on:
      - openvoxdb

  puppet-compiler:
    image: ghcr.io/openvoxproject/openvoxserver:${PUPPET_SERVER_TAG}
    platform: linux/amd64
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      # The mounted onto path '/conjur' is a proxy location that allows us to decide, at
      # runtime, between installing the packaged module or using the module source.
      - ../../.:/conjur
    environment:
      - CA_ENABLED=false
      - CA_HOSTNAME=puppet
      - OPENVOXSERVER_HOSTNAME=puppet-compiler
      - DNS_ALT_NAMES=puppet,puppet-compiler
      - HIERACONFIG=/etc/puppetlabs/code/hiera.yaml
    depends_on:
      - puppet
      - openvoxdb

  openvoxdb:
    image: ghcr.io/openvoxproject/openvoxdb:latest
    depends_on:
      - postgres

  postgres:
    image: docker.io/postgres:alpine
    hostname: postgres
    environment:
      POSTGRES_DB: openvoxdb
      POSTGRES_USER: openvoxdb
      POSTGRES_PASSWORD: openvoxdb
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U openvoxdb -d openvoxdb'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./postgresql_init:/docker-entrypoint-initdb.d

  conjur:
    image: cyberark/conjur
    platform: linux/amd64
    ports:
      - 80
    environment:
      CONJUR_ADMIN_PASSWORD: ADmin123!!!!
      DATABASE_URL: postgres://postgres:SuperSecretPg@conjur-db/postgres
      CONJUR_DATA_KEY: testing//testing//testing//testing//testing=
    #volumes:
    #  - .:/src:ro
    #working_dir: /src
    command: server
    depends_on:
      - conjur-db


  conjur-https:
    image: nginx:alpine
    platform: linux/amd64
    ports:
      - 8443
    volumes:
      - ./https_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./https_config/conjur.conf:/etc/nginx/sites-enabled/conjur.conf:ro
      - ./https_config/dhparams.pem:/etc/nginx/dhparams.pem:ro
      - ./https_config/conjur.crt:/cert/tls.crt:ro
      - ./https_config/conjur.key:/cert/tls.key:ro
      - ./https_config/ca.crt:/ca/tls.crt:ro
    depends_on:
      - conjur
    networks:
      default:
        aliases:
          - conjur.cyberark.com

  conjur-db:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_PASSWORD: SuperSecretPg
    ports:
      - 8432:5432
  cli:
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_APPLIANCE_URL: http://conjur
    image: cyberark/conjur-cli
    platform: linux/amd64
    entrypoint: sleep
    command: infinity
    volumes:
      - .:/src:ro
