FROM ruby:3.4.1-slim
LABEL org.opencontainers.image.authors="CyberArk Software Ltd."

# Install PDK (https://puppet.com/docs/pdk/1.x/pdk_install.html)
RUN apt-get update && \
    apt-get install -y docker build-essential curl make && \
    curl -L "https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=debian&rel=10&arch=amd64&ver=latest" -o pdk.deb && \
    dpkg -i pdk.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /conjur
WORKDIR /conjur

COPY . /conjur
