FROM ruby:2.5
MAINTAINER CyberArk Software Ltd.

# Install PDK (https://puppet.com/docs/pdk/1.x/pdk_install.html)
RUN wget -q https://apt.puppet.com/puppet-tools-release-stretch.deb && \
    dpkg -i puppet-tools-release-stretch.deb && \
    apt-get update && \
    apt-get install pdk

RUN mkdir /conjur
WORKDIR /conjur

COPY . /conjur
